[build]
  publish = "client/dist"
  command = "cd client && npm install --legacy-peer-deps && npm run build && cd .. && cp -r attached_assets client/dist/ || true"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}

# API function routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Function settings for image processing
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Increase timeout for image processing functions
[functions."icons/*"]
  timeout = 30

# Environment variables configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"